name: Android Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
#        java-version: '11'
#        distribution: 'temurin'
#        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Execute unit tests
    - name: Unit Test
      run: ./gradlew test

    # Report the results
    - name: Android Test Report
      uses: asadmansr/android-test-report-action@v1.2.0
      if: ${{ always() }} # IMPORTANT: run Android Test Report regardless
