name: Android Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

  androidTest:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      # Execute instrumentation tests
      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86
          disable-animations: true
          script: ./gradlew connectedAndroidTest --stacktrace

      # Execute unit tests
      - name: Unit Test
        run: ./gradlew testDebugUnitTest

    # Report the results
  report:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ always() }} # IMPORTANT: run Android Test Report regardless
    steps:
      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
